services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:4173"
    depends_on:
      - backend
    networks:
      acronis_network:
        ipv4_address: 172.16.100.4

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "5000:5000"
    networks:
      acronis_network:
        ipv4_address: 172.16.100.5

# Network configuration
networks:
  acronis_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/29
